#ifndef MCP3561
#define MCP3561

#define WRITE_COMMAND_MASK 0x02
#define READ_COMMAND_MASK 0x01

#define ADCDATA_REGISTER 0x0
#define CONFIG0_REGISTER_ADDRESS 0x1
#define CONFIG1_REGISTER_ADDRESS 0x2
#define CONFIG2_REGISTER_ADDRESS 0x3
#define CONFIG3_REGISTER_ADDRESS 0x4
#define INTERRUPT_REQUEST_REGISTER 0x5
#define MULTIPLEXER_REGISTER 0x6
#define SCAN_MODE_SETTINGS_REGISTER 0x7
#define TIMER_DELAY_VALUE_REGISTER 0x8
#define OFFSET_CALIBRATION_REGISTER 0x9
#define GAINCAL_REGISTER 0xA

#define DEVICE_ADDRESS 0x00
#define DEVICE_ADDRESS_MASK DEVICE_ADDRESS << 6
#define CONFIG0_CLK_SELECT_OFFSET 4
#define CONFIG0_ADC_MODE_OFFSET 0

#define INTERNAL_CLOCK_NO_OUTPUT 0x03 
#define ADC_CONVERSION_MODE 0x03

#define COMMAND_ADDRESS_POSITION 2 
#define WRITE_COMMAND DEVICE_ADDRESS_MASK | WRITE_COMMAND_MASK

#define CONFIG0_WRITE WRITE_COMMAND | (CONFIG0_REGISTER_ADDRESS << COMMAND_ADDRESS_POSITION)  

void setup_MCP3561(void);

#endif
